language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
services:
  - redis-server
install:
  - pip install -e .
  - pip install coverage>=4.0a5 coveralls
  - pip install hiredis
  - "if [[ $TEST_PEP8 == '1' ]]; then pip install pep8; fi"
script: "bash ./travis-script.sh"
matrix:
  include:
    - python: "2.7"
      env: TEST_PEP8=1
    - python: "3.4"
      env: TEST_PEP8=1
after_success:
  - coverage combine
  - coveralls
